# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../list_favorites'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'moviesApp_viewCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  inherit! :search_paths
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  pod 'RealmSwift', '=10.1.4'

  target 'moviesApp_viewCodeTests' do
    inherit! :search_paths
    use_frameworks!
    # Pods for testing
    pod 'iOSSnapshotTestCase'
  end

  target 'moviesApp_viewCodeUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
   end
  end
 end
