name: Run CI
on: pull_request

jobs:
  ci:
    name: CI Flutter
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java version 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter version 2.0.0
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'

      - name: Dart Version
        run: dart --version

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Test
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: flutter test --dart-define=APIKEY=$APIKEY --coverage

      - name: Generate coverage report XML
        run: ./scripts/lcovToXML.py coverage/lcov.info -b lib -o coverage/coverage.xml

      - name: Post coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage.xml

      - name: Load iOS Simulator
        run: |
          xcrun simctl boot F2707416-A4C6-4BCC-985B-8B3697376592

      - name: Load Android Simulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: Pixel 4
          script: ./gradlew connectedCheck

      - name: UI Test
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          flutter devices
          flutter driver --target=test_driver/favoriteFlow/favoriteFlow.dart --dart-define=APIKEY=$APIKEY -d F2707416-A4C6-4BCC-985B-8B3697376592

      - name: Build
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: flutter build apk --dart-define=APIKEY=$APIKEY
        

